server:
  port: 9001

spring:
  datasource:
    #   数据源基本配置
    username: xx
    password: xx
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xx/xx?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: xxx
    port: 6379
    password: xxx
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true #自动开启驼峰规则映射
    call-setters-on-nulls: true               #map数据为空的字段，则返回null
  global-config:
    db-config:
      id-type: AUTO
      table-underline: true

alimnscloud:
  alimnsAccessId: xxx
  alimnsAccessKey: xxxx
  alimnsEndpoint:
  aliSmsTemplateId: xxx
  aliSignatureName: xxx

aliosscloud:
  bucketName: xxx                               #已经在控制台创建的bucket
  picLocation: xxx/                            #你上传文件的保存路径，如果bucket中不存在则创建（其实原理并不是文件夹，只是文件名，详情请先阅读官方文档）
  aliossEndpoint: oss-cn-beijing.aliyuncs.com
  aliossAccessId: xxxx
  aliossAccessKey: xxxx


wx:
  mp:
    configs:
      appId: xx
      secret: xx
      template1: x
      template2: QBf9rP8-x
