server:
  port: 9001

spring:
  datasource:
    #   数据源基本配置
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/froms_three2?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true #自动开启驼峰规则映射
    call-setters-on-nulls: true               #map数据为空的字段，则返回null
  global-config:
    db-config:
      id-type: AUTO
      table-underline: true
wx:
  mp:
    configs:
      appId: wxb1ed5f52a20b621f
      secret: f224e88737b8bc65aeb37a8ee3b7d1b7
